url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: JB Designed
email: jason@jbdesigned.com
description: "Welcome to JB Designed. Where quality leather and expert craftsmanship come together with a design created with you."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: github
    url: http://github.com/pacoustic

# Postal address (add as many lines as necessary)
address:
  - line: 300 Loomis Ave
  - line: Des Moines, IA 50315

# Build settings
markdown: kramdown
permalink: pretty